services:
  task-planner:
    image: timk1111111/task-planner:latest
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    image: timk1111111/task-planner-frontend:latest
    restart: unless-stopped
    ports:
      - "5173:80"

  summarization-service:
    image: timk1111111/summarization-service:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

  scheduler:
    image: timk1111111/scheduler:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

  email-sender:
    image: timk1111111/email-sender:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

  db:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    container_name: tasks_planner_postgres_compose
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - tasks_planner_postgres_data:/var/lib/postgresql/data

  kafka:
    image: ${KAFKA_IMAGE}
    restart: unless-stopped
    container_name: kafka_compose
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    volumes:
      - tasks_planner_kafka_data:/tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

volumes:
  tasks_planner_postgres_data:
  tasks_planner_kafka_data: