name: Task Planner CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'
      - 'gradlew'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_TASK_PLANNER }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TASK_PLANNER }}

      - name: Build and push Task Planner
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME_TASK_PLANNER }}/task-planner:latest
            ${{ secrets.DOCKERHUB_USERNAME_TASK_PLANNER }}/task-planner:${{ github.sha }}
